apiVersion: batch/v1
kind: Job
metadata:
  name: deployment-writer
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: deployment-writer
          image: deployment-writer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_ID
              valueFrom:
                secretKeyRef:
                  name: argocd-notifications-secret
                  key: app_id
            - name: OWNER
              value: {{ .Values.deployment.owner }}
            - name: REPO
              value: {{ .Values.deployment.repo }}
            - name: REF
              value: {{ .Values.deployment.sha }}
            - name: ENVIRONMENT
              value: {{ .Values.deployment.environment }}
            - name: PRIVATE_KEY_PATH
              value: "/keys/pk" 
          volumeMounts:
            - name: github-app-key
              mountPath: /keys
              readOnly: true
      volumes:
        - name: github-app-key
          secret:
            secretName: argocd-notifications-secret
